# Item 1
[[questions]]
question = "Which of the following best describes a programming paradigm?"
answer = "a style or model for solving problems <br>using specific programming concepts"
alternatives = [
"a method for compiling code <br>into machine language",
"a system for organizing files and folders",
"a type of software license"
]
