# Item 1
[[questions]]
question = "Which of the following best describes functional programming?"
answer = "A paradigm that treats computation as <br>the evaluation of mathematical functions"
alternatives = [
"A paradigm focused on step-by-step procedures",
"A paradigm based on objects and inheritance",
"A paradigm that manipulates hardware directly"
]