# Item 1
[[questions]]
question = "Which of the following best describes a <br>programming paradigm?"
answer = "A style or approach to programming"
alternatives = ["A method of debugging programs", "A programâ€™s syntax", "A compiler structure"]

# Item 2
[[questions]]
question = "The imperative paradigm focuses on:"
answer = "Describing how to perform <br>operations step-by-step"
alternatives = ["Describing what result <br>should be obtained", "Describing relationships <br>among facts", "Avoiding mutable data"]
