# Item 1
[[questions]]
question = "Which of the following best describes a <br>programming paradigm?"
answer = "A style or approach to programming"
alternatives = ["A method of debugging programs", "A programâ€™s syntax", "A compiler structure"]
