# Item 1
[[questions]]
question = "What does encapsulation refer to in OOP?"
answer = "Combining data and methods <br>into a single unit"
alternatives = ["Hiding data in global variables", "Inheriting attributes from a superclass", "Overriding methods"]
